baseURL: "http://qinry.github.io/"
title: "qinry's blog"
theme: "hyde"

paginate: 6


# theme is hyde
Menus:
   main:
     - Name: "Github"
       URL: "https://github.com/qinry"
     - Name: "Categories"
       URL: "https://qinry.github.io/categories"
Params:
   description: "在此写下学习日志，努力充电中～"
