baseURL = "https://qinry.github.io"
title = "qinry's blog"
theme = "m10c"

paginate = 6
[params]
   author = "qinry"
   description = "在此写下学习日志，努力充电中～"
   [[params.social]]
   	name = "github"
	url = "https://github.com/qinry"
